version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing" # encho = printout
      - run: npm install
      - run: CI=true npm run build # CI=true define env variable CI = true
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hellllooooo!"
workflows:
  version: 2
  build_test_and_lint: # workflow name
    jobs:
      - build # run parallel
      - hithere # run parallel
      - test:
          requires: # test job require hithere job to finish and succed
            - hithere
